### PR TITLE
Use ActiveSupport's constantize

### LINKED ISSUE #115: Use ActiveSupport's constantize if it exists
```
$ rails c
Loading development environment (Rails 4.2.1)

irb(main):001:0> string = "Fulfiller::Jobs::SunFrog::SendOrders"
=> "Fulfiller::Jobs::SunFrog::SendOrders"

irb(main):002:0> string.split('::').inject(Object, &:const_get)
NameError: uninitialized constant SunFrog::SendOrders
	from (irb):2:in `const_get'
	from (irb):2:in `each'
	from (irb):2:in `inject'
	from (irb):2

irb(main):003:0> string.constantize
=> Fulfiller::Jobs::SunFrog::SendOrders
```

https://github.com/chanks/que/blob/master/lib/que/job.rb#L140 -- using const_get doesn't work perfectly with Rails's autoloading (I also have a top-level SunFrog constant).

### PR DESCRIPTION
**Pull request by joevandyk**
Fixes #115

### CODE REVIEW

**Comment by joevandyk** [comment]
I was not able to get any tests to show the bug. :/

**Comment by chanks** [comment]
Hmm, that's disconcerting. I want to give it a shot myself before merging.

**Comment by joevandyk** [comment]
Another option is to use Sidekiq's version: 
https://www.omniref.com/ruby/gems/sidekiq/0.6.0/symbols/Sidekiq::Util/constantize

Resque seems to copy over the implementation: 
https://github.com/resque/resque/blob/master/lib/resque/core_ext/string.rb

I updated the commit with using String#constanize if it exists. I'm not sure what the best method is.

**Comment by chanks** [comment]
Tried a bit to write a failing spec and couldn't, but oh well, it's not a bad idea anyways.

Will be releasing 0.11.0 in just a bit.

**Comment by joevandyk** [comment]
I wasn't sure if you would want to use the methods that Sidekiq or Resque use. (It's too bad this isn't a standard Ruby method)

**Comment by chanks** [comment]
I think keeping the current method if ActiveSupport isn't present is fine.
If someone not using ActiveSupport runs into it we can import one of those
methods later.

And I just realized I forgot to update the changelog with this fix before I
cut the new version, but I'll do it now.

**Pull request merged**
