### PR TITLE
Test against rails 6

### PR DESCRIPTION
**Pull request by siegy22**
https://weblog.rubyonrails.org/2019/4/24/Rails-6-0-rc1-released/

### CODE REVIEW

**Comment by siegy22** [comment]
@chanks just a question in general, why is the `Gemfile.lock` ignored?

**Comment by siegy22** [comment]
@chanks Is the ci configuration broken? Or why is there no build to this?

**Comment by chanks** [comment]
Not sure how/if CircleCI works with pull requests, sorry.

**Comment by airhorns** [comment]
This'd be awesome to get in! And, to get this tested I think you'd need to turn this setting on for circle https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories which will test PRs from forked repos like this one. It looks like its safe to do that because there's no secrets or sensitive data in the circle environment for the main repo but that page has more information on the risks associated with turning that option on.

**Comment by siegy22** [comment]
-> https://github.com/que-rb/que/pull/2

**Pull request closed without merging**
