### PR TITLE
Warn about concurrency and plain PG connection

### PR DESCRIPTION
**Pull request by tpitale**

### CODE REVIEW

**Comment by chanks** [comment]
It hadn't even occurred to me when trying to diagnose your problem that you'd be using the single PG connection. I think I only added it in the first place so that the range of adapters would be more complete, and not because it'd actually really be useful to anyone.

Do you have a good reason for using a single connection rather than a pool? If not, I'm tempted to just remove that section from the docs entirely.

**Comment by tpitale** [comment]
I switched to a connection. I think removing it as an example is a good idea. I would replace or promote the PG connection in a simple pool as the supported solution if you don't use AR.

I was using it because my project doesn't use AR.

**Comment by tpitale** [comment]
*connection pool*

**Comment by chanks** [comment]
Alright, removed. Sorry that was such a pain.

**Comment by tpitale** [comment]
Oh, not your fault at all. Thanks for all the help!

**Pull request closed without merging**
