### PR TITLE
Sync stdout

### PR DESCRIPTION
**Pull request by hmarr**
@sinjo review?

### CODE REVIEW

**Comment by hmarr** [comment]
Apologies - submitted to the wrong repo! Github defaults to opening PRs against the upstream.

**Comment by chanks** [comment]
No problem!

**Comment by hmarr** [comment]
Cheers :)

However, on that note, would you accept a PR with the changes in [this commit](https://github.com/gocardless/que/commit/11ea2a3cde781e55026d5d9185512cd49bc6ac27)? [Sidekiq](https://github.com/mperham/sidekiq/blob/0fd04ba0ea86fb44c3b8e34e98aea8a877f1b2ed/lib/sidekiq/cli.rb#L2), [Unicorn](https://github.com/defunkt/unicorn/blob/422a657a5f6dfb69f44feabd6429f2904ca03fa8/lib/unicorn/launcher.rb#L4), and friends all seem to do it, and it's currently stopping us from getting logs in some cases.

**Comment by chanks** [comment]
Sure, looks reasonable!

**Comment by hmarr** [comment]
Awesome, will put a PR in.

**Pull request closed without merging**
