### PR TITLE
Only call parse on JSON_MODULE if it's defined

### PR DESCRIPTION
**Pull request by rwz**
This addresses https://github.com/chanks/que/issues/189

### CODE REVIEW

**Comment by chanks** [comment]
Hey, thanks @rwz. @hmac, who pointed out the issue initially, also realized that there'd be a problem with MultiJson. I'm trying to figure out whether it's safe to just always call `JSON_MODULE.load(json, create_additions: false)`

**Comment by chanks** [comment]
Yeah, it seems that way to me. I just pushed a fix to master, would you verify that it works for you? If it does I'll cut a new release.

**Comment by rwz** [comment]
This is very likely to fix the issue for our codebase that has MultiJson in it. Seems like we'd also wanna someone with stdlib JSON to weight in. Or... I guess all the specs are exercising no-MultiJson case, so it's probably a good enough warranty?

**Comment by chanks** [comment]
Yeah, that's my thinking, I'm not worried about the stdlib case. Is it convenient for you to test this, just to double-check that MultiJson works? If not I suppose I'll just release - it's a pretty simple fix, seems to me.

While we're here, I'm wondering if there's a compelling use-case anymore for Que to use MultiJson at all? Way back when it was introduced I believe the rationale was that stdlib had poor performance, but I'm not sure that that's true these days? I'm kind of inclined to remove support (in a major version bump) for simplicity's sake.

**Comment by rwz** [comment]
Yeah, our CI's just verified that master works fine.

**Comment by chanks** [comment]
Alright, released 0.12.3.

**Comment by rwz** [comment]
Cool, thanks!

**Comment by chanks** [comment]
Hey @rwz, I just pushed a change to master to drop support for MultiJson, since it doesn't seem to be necessary anymore and removing it simplifies things (see #191). When it's convenient would you check and make sure that the current master works for you?

Thanks!

**Comment by rwz** [comment]
I can check now. Will report back in a few.

**Comment by rwz** [comment]
We're green.

**Pull request closed without merging**
